# Inventory Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: order-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
      - name: inventory-service
        image: inventory-service:latest
        imagePullPolicy: Never  # For local Minikube development
        ports:
        - containerPort: 3001
        env:
        - name: PORT
          value: "3001"
        - name: MONGODB_URI
          value: "mongodb://mongodb-inventory-service:27017/inventory"
        - name: NODE_ENV
          value: "production"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: order-management
spec:
  selector:
    app: inventory-service
  ports:
  - port: 3001
    targetPort: 3001
  type: ClusterIP