# MongoDB for Shipping Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-shipping
  namespace: order-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-shipping
  template:
    metadata:
      labels:
        app: mongodb-shipping
    spec:
      containers:
      - name: mongodb
        image: mongo:6.0
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_DATABASE
          value: "shipping"
        volumeMounts:
        - name: mongodb-storage
          mountPath: /data/db
      volumes:
      - name: mongodb-storage
        persistentVolumeClaim:
          claimName: mongodb-shipping-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-shipping-service
  namespace: order-management
spec:
  selector:
    app: mongodb-shipping
  ports:
  - port: 27017
    targetPort: 27017
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-shipping-pvc
  namespace: order-management
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi