# Order Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: order-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: order-service:latest
        imagePullPolicy: Never  # For local Minikube development
        ports:
        - containerPort: 3002
        env:
        - name: PORT
          value: "3002"
        - name: MONGODB_URI
          value: "mongodb://mongodb-orders-service:27017/orders"
        - name: INVENTORY_SERVICE_URL
          value: "http://inventory-service:3001"
        - name: RABBITMQ_URL
          value: "amqp://admin:admin123@rabbitmq-service:5672"
        - name: NODE_ENV
          value: "production"
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: order-management
spec:
  selector:
    app: order-service
  ports:
  - port: 3002
    targetPort: 3002
  type: ClusterIP