# Shipping Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service
  namespace: order-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shipping-service
  template:
    metadata:
      labels:
        app: shipping-service
    spec:
      containers:
      - name: shipping-service
        image: shipping-service:latest
        imagePullPolicy: Never  # For local Minikube development
        ports:
        - containerPort: 3003
        env:
        - name: PORT
          value: "3003"
        - name: MONGODB_URI
          value: "mongodb://mongodb-shipping-service:27017/shipping"
        - name: RABBITMQ_URL
          value: "amqp://admin:admin123@rabbitmq-service:5672"
        - name: NODE_ENV
          value: "production"
        livenessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: shipping-service
  namespace: order-management
spec:
  selector:
    app: shipping-service
  ports:
  - port: 3003
    targetPort: 3003
  type: ClusterIP